services:
  laravel:
    build:
      context: .
      target: prod
    user: "${WWWUSER-web}:${WWWGROUP-1000}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${SERVER_NAME}:0.0.0.0'
    ports:
      - '${APP_PORT:-80}:80'
      - '443:443'
      - '443:443/udp'
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: 'mariadb:11'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ROOT_HOST: '%'
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
      - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    healthcheck:
      test: [ CMD, healthcheck.sh, '--connect', '--innodb_initialized' ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    healthcheck:
      test: [ CMD, redis-cli, ping ]
      retries: 3
      timeout: 5s

volumes:
  mariadb:
    driver: local
  redis:
    driver: local
