services:
  laravel:
    extends:
      file: compose.common.yaml
      service: laravel
    build:
      target: dev
      args:
        USER: "${WWWUSER-www-data}"
    depends_on:
      - mailpit
    user: "${WWWUSER-www-data}"
    ports:
      - "80:80"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    hostname: '${SERVER_NAME:-laravel.local}'
    # Start Octane in worker mode
    command: ["${APP_BASE_PATH:-/var/www/html}/deployment/dev/start-container-dev.sh"]
    environment:
      # noinspection HttpUrlsUsage
      CADDY_HTTP_SERVER_ADDRESS: "http://${SERVER_NAME:-laravel.localhost}"
      CADDY_HTTPS_SERVER_ADDRESS: "https://${SERVER_NAME:-laravel.localhost}"
      IGNITION_EDITOR: '${IGNITION_EDITOR:-vscode}'
      IGNITION_REMOTE_SITES_PATH: '/var/www/html'
      LARAVEL_SAIL: 1
      PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=Sail}'
      TERMINAL_EMULATOR: ${TERMINAL_EMULATOR:-Jetbrains-JediTerm}
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug,develop}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal log=/tmp/xdebug.log}'
      WEBSERVER: ${WEBSERVER:-octane-watch}
    volumes:
      - '.:/var/www/html'
      - ~/.config/composer/auth.json:/composer/auth.json:rw
      - ~/.cache/composer:/composer/cache:rw
      - ~/.bun/install/cache:/home/${WWWUSER:-www-data}/.bun/install/cache:rw
      - ~/.caddy/ca:/data/caddy/pki/authorities/local:rw
      - /tmp/sitekit:/tmp/sitekit

  task:
    extends:
      file: compose.common.yaml
      service: task
    build:
      target: dev
    volumes:
      - '.:/var/www/html'

  queue:
    extends:
      file: compose.common.yaml
      service: queue
    build:
      target: dev
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql
      - redis

  mysql:
    extends:
      file: compose.common.yaml
      service: mysql
    volumes:
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  redis:
    extends:
      file: compose.common.yaml
      service: redis

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    healthcheck:
      test: [ "CMD", "/mailpit", "readyz" ]
      interval: 15s

volumes:
  caddy_config:
  caddy_data:
  mysql:
  redis:
