services:
  laravel:
    restart: unless-stopped
    build:
      context: .
      target: prod
    user: "${WWWUSER-www-data}"
    extra_hosts:
      - '${SERVER_NAME:-laravel.localhost}:127.0.0.1'
    ports:
      - '${APP_PORT:-80}:80'
    env_file:
      - .env
    # Set healthcheck to use our native healthcheck script for Octane
    healthcheck:
      test: ["CMD", "healthcheck-octane"]
      start_period: 10s
    environment:
      CADDY_GLOBAL_OPTIONS: |
        log file {
            output file /var/log/frankenphp/frankenphp.log {
                roll_size 10MiB
                roll_keep 5
            }
        }
      CADDY_PHP_SERVER_OPTIONS: |
        index frankenphp-worker.php
        try_files {path} frankenphp-worker.php
        # Required for the public/storage/ directory...
        resolve_root_symlink
      CADDY_SERVER_EXTRA_DIRECTIVES: |
        log access {
            format json
            output file /var/log/frankenphp/access.log {
                roll_size 10MiB
                roll_keep 5
            }
        }
      FRANKENPHP_CONFIG: |
        worker {
          file "${APP_PUBLIC_PATH:-/var/www/html/public}/frankenphp-worker.php"
        }
    volumes:
      - caddy_config:/config:rw
      - caddy_data:/data:rw
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    security_opt:
      - no-new-privileges:true

  task:
    restart: unless-stopped
    build:
      context: .
      target: prod
    command: ["unbuffer", "php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "healthcheck-schedule"]
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true

  queue:
    restart: unless-stopped
    build:
      context: .
      target: prod
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    stop_signal: SIGTERM
    healthcheck:
      # This is our native healthcheck script for the queue
      test: ["CMD", "healthcheck-queue"]
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true

  horizon:
    restart: unless-stopped
    build:
      context: .
      target: prod
    command: ["php", "/var/www/html/artisan", "horizon"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "healthcheck-horizon"]
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true

  mysql:
    restart: unless-stopped
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-$DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
    healthcheck:
      test: [ CMD, mysqladmin, ping, '-p${DB_PASSWORD}' ]
      retries: 3
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    cap_add: [CHOWN, SETUID, SETGID, DAC_OVERRIDE]

  redis:
    restart: unless-stopped
    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    healthcheck:
      test: [ CMD, redis-cli, ping ]
      retries: 3
      timeout: 5s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    cap_add: [CHOWN, SETUID, SETGID, DAC_OVERRIDE]

volumes:
  caddy_config:
  caddy_data:
  mysql:
  redis:
