services:
  laravel:
    extends:
      file: docker-compose.common.yml
      service: laravel
    build:
      target: dev
    user: "${WWWUSER-sail}:${WWWGROUP-1000}"
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    hostname: '${SERVER_NAME:-laravel.local}'
    environment:
      WEBSERVER: octane-watch
      #            WWWUSER: '${WWWUSER:-1000}'
      #            WWWGROUP: '${WWWGROUP:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug,develop}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal log=/tmp/xdebug.log}'
      PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=Sail}'
      IGNITION_EDITOR: '${IGNITION_EDITOR:-vscode}'
      IGNITION_REMOTE_SITES_PATH: '/app'
      SUPERVISOR_USER: sail
      SUPERVISOR_PHP_USER: sail
      SUPERVISOR_VITE_USER: sail
    #            SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --host=localhost --port=443 --admin-port=2019 --https"
    volumes:
      - '.:/var/www/html'
      - ~/.caddy/ca:/var/www/html/.data/caddy/pki/authorities/local

  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql
    volumes:
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  memcached:
    extends:
      file: docker-compose.common.yml
      service: memcached

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    healthcheck:
      test: [ "CMD", "/mailpit", "readyz" ]
      interval: 15s

volumes:
  mysql:
    driver: local
  redis:
    driver: local
