services:
  laravel:
    extends:
      file: docker-compose.common.yml
      service: laravel
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      memcached:
        condition: service_healthy

  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql

  redis:
    extends:
      file: docker-compose.common.yml
      service: redis

  memcached:
    extends:
      file: docker-compose.common.yml
      service: memcached

volumes:
  mysql:
    driver: local
  redis:
    driver: local
